# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8082
    servlet:
        context-path: /renren-generator

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/renren_security?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

# mysql逆向生成
generator:
   project: renren-admin
   moduleName: cms
   packageName: io.renren.modules
   table: article
   menuName: 文章管理
   columnList:
      -  id int(10) unsigned NOT NULL AUTO_INCREMENT ,
      -  article_category_id int NULL DEFAULT 0,
      -  article_title varchar(128) NULL ,
      -  article_desc varchar(256) NULL ,
      -  artical_body TEXT NULL ,
      -  status tinyint(2) NOT NULL DEFAULT 0 ,
      -  meta_title varchar(128) NULL ,
      -  meta_desc varchar(256) NULL ,
      -  updated_at datetime NULL ,
      -  created_at datetime NULL ,
      -  PRIMARY KEY (id)


